export interface Technique {
  id: string;
  title: string;
  description: string;
  difficulty: 'Beginner' | 'Advanced' | 'Expert';
  category: string;
  steps: string[];
  tools: string[];
  notes: string;
}

export const TECHNIQUES: Technique[] = [
  {
    id: "ssl-pinning",
    title: "SSL Pinning Bypass",
    description: "تجاوز حماية شهادات SSL لمراقبة حركة مرور HTTPS المشفرة.",
    difficulty: "Advanced",
    category: "Network",
    tools: ["Frida", "objection", "Burp Suite"],
    steps: [
      "قم بتثبيت Frida-server على الجهاز المستهدف.",
      "قم بإعداد Burp Suite واعتراض حركة المرور.",
      "استخدم objection للبحث عن كود التحقق من الشهادات.",
      "قم بتشغيل الأمر 'android sslpinning disable' في objection.",
      "في حالة الفشل، استخدم سكربت Frida مخصص للـ Hooks العميقة.",
      "تأكد من تثبيت شهادة Burp كشهادة نظام (System Certificate).",
      "راقب حركة المرور الآن في Burp Suite.",
    ],
    notes: "يتطلب أحياناً تعديل الـ Binary في حالة الحماية القوية جداً.",
  },
  {
    id: "root-detection",
    title: "Root Detection Bypass",
    description: "تجاوز فحص الروت الذي تفرضه بعض التطبيقات البنكية والأمنية.",
    difficulty: "Advanced",
    category: "Security",
    tools: ["Magisk", "Shamiko", "Frida"],
    steps: [
      "استخدم Magisk مع تفعيل Zygisk.",
      "قم بتثبيت إضافة Shamiko لإخفاء الروت بذكاء.",
      "أضف التطبيق المستهدف إلى قائمة الـ DenyList في Magisk.",
      "في حالة استمرار الكشف، استخدم سكربت Frida (root-bypass-script).",
      "قم بتبديل أسماء الملفات المشبوهة مثل su و magisk.",
      "استخدم 'objection' للأتمتة السريعة عبر 'android root disable'.",
    ],
    notes: "بعض التطبيقات تستخدم Play Integrity التي تتطلب حلولاً أكثر تعقيداً.",
  },
  {
    id: "static-workflow",
    title: "Static Analysis Workflow",
    description: "مسار العمل المثالي لتحليل التطبيق دون تشغيله.",
    difficulty: "Beginner",
    category: "Static",
    tools: ["JADX", "APKTool", "Ghidra"],
    steps: [
      "ابدأ بـ JADX-GUI لفتح الـ APK وقراءة كود Java.",
      "استخدم APKTool لفك الملف (d) لاستخراج الـ Resources و Smali.",
      "ابحث عن الكلمات المفتاحية مثل 'password', 'key', 'API' في JADX.",
      "إذا وجد كود Native، استخرج ملفات .so وافتحها في Ghidra.",
      "قم بمطابقة منطق Java مع استدعاءات الـ Native Code.",
    ],
    notes: "التحليل الساكن هو الخطوة الأولى والأهم في أي عملية هندسة عكسية.",
  },
  {
    id: "dynamic-setup",
    title: "Dynamic Analysis Setup",
    description: "تجهيز بيئة التحليل الديناميكي لمراقبة التطبيق أثناء العمل.",
    difficulty: "Beginner",
    category: "Dynamic",
    tools: ["ADB", "Frida", "Genymotion"],
    steps: [
      "قم بتشغيل محاكي Genymotion أو جهاز حقيقي مع صلاحيات روت.",
      "تأكد من تفعيل USB Debugging واتصال ADB.",
      "ارفع frida-server إلى /data/local/tmp/ وقم بتشغيله كروت.",
      "تأكد من مطابقة إصدار frida-client على الكمبيوتر مع الـ server.",
      "ابدأ بحقن السكربتات الأساسية لمراقبة الـ Logs والدوال.",
    ],
    notes: "يُفضل دائماً استخدام جهاز حقيقي للنتائج الأكثر دقة.",
  },
  {
    id: "smali-patching",
    title: "Smali Patching",
    description: "تعديل سلوك التطبيق عن طريق تحرير كود الـ Smali مباشرة.",
    difficulty: "Expert",
    category: "Static",
    tools: ["APKTool", "Text Editor", "Uber APK Signer"],
    steps: [
      "فك الـ APK باستخدام apktool d app.apk.",
      "ابحث عن ملف الـ Smali الذي يحتوي على المنطق المراد تعديله.",
      "قم بتغيير التعليمات (مثل if-eqz إلى if-nez لتغيير شرط التحقق).",
      "أعد بناء الـ APK باستخدام apktool b output/.",
      "وقع الـ APK الجديد باستخدام Uber APK Signer.",
      "قم بتثبيت الـ APK المعدل واختباره.",
    ],
    notes: "يتطلب معرفة جيدة بلغة الـ Smali وهيكلية JVM/Dalvik.",
  },
  {
    id: "network-interception",
    title: "Network Interception",
    description: "اعتراض وتحليل طلبات الشبكة بين التطبيق والخادم.",
    difficulty: "Beginner",
    category: "Network",
    tools: ["Burp Suite", "mitmproxy", "WiFi Proxy"],
    steps: [
      "قم بإعداد Proxy على جهاز الأندرويد ليوجه الحركة للكمبيوتر.",
      "ثبت شهادة الـ CA الخاصة بـ Burp Suite على الجهاز.",
      "استخدم Burp Suite Intercept لمشاهدة الطلبات (Requests).",
      "قم بتعديل البيانات المرسلة في الوقت الفعلي لاختبار الـ Backend.",
      "استخدم الـ Repeater لإعادة إرسال الطلبات مع تغييرات بسيطة.",
    ],
    notes: "تطبيقات أندرويد 7+ تتطلب إعدادات خاصة في network_security_config.xml.",
  },
  {
    id: "obfuscation-reversal",
    title: "Obfuscation Reversal",
    description: "استعادة أسماء الدوال والمتغيرات الأصلية من الكود المبهم.",
    difficulty: "Expert",
    category: "Static",
    tools: ["JADX", "ProGuard", "Frida"],
    steps: [
      "استخدم ميزة Deobfuscation في JADX لتعيين أسماء افتراضية.",
      "ابحث عن String constants التي قد تكشف وظيفة الدالة.",
      "استخدم Frida لعمل Hooks وتصوير الـ Stack Trace وقت التنفيذ.",
      "قم بإنشاء ملف mapping مخصص لتغيير الأسماء تدريجياً.",
      "قارن النسخ القديمة والجديدة من التطبيق إذا كانت متوفرة.",
    ],
    notes: "عملية مرهقة وتعتمد بشكل كبير على الحدس والخبرة.",
  },
  {
    id: "native-analysis",
    title: "Native Library Analysis",
    description: "تحليل ملفات C++ (.so) المستخدمة في الأندرويد.",
    difficulty: "Expert",
    category: "Static",
    tools: ["Ghidra", "Radare2", "IDA Pro"],
    steps: [
      "استخرج ملفات الـ .so من مجلد lib/ داخل الـ APK.",
      "افتح الملف في Ghidra وقم بعمل تحليل (Analysis) كامل.",
      "ابحث عن JNI_OnLoad لمعرفة كيفية تسجيل الدوال.",
      "استخدم الـ Decompiler لرؤية كود C تقريبي.",
      "ابحث عن استدعاءات التشفير والعمليات الحساسة.",
    ],
    notes: "أصعب أنواع الهندسة العكسية ولكنها الأكثر أهمية للحماية القوية.",
  },
  {
    id: "safetynet-bypass",
    title: "SafetyNet/Play Integrity Bypass",
    description: "تجاوز فحوصات سلامة الجهاز من جوجل.",
    difficulty: "Expert",
    category: "Security",
    tools: ["Magisk", "Play Integrity Fix", "LSPosed"],
    steps: [
      "تأكد من مرور فحص Basic Integrity و Device Integrity.",
      "استخدم إضافة Play Integrity Fix المحدثة دائماً.",
      "قم بإخفاء Magisk عن طريق إعادة تسمية الحزمة.",
      "تجنب تفعيل خيارات الـ Developer إلا للضرورة.",
      "استخدم كيرنل (Kernel) مخصص إذا لزم الأمر لإخفاء حالة الـ Bootloader.",
    ],
    notes: "جوجل تحدث هذه الفحوصات باستمرار مما يتطلب متابعة دائمة.",
  },
  {
    id: "memory-dump",
    title: "Custom ClassLoader Dump",
    description: "استخراج كود الـ DEX من الذاكرة في حالة التشفير القوي.",
    difficulty: "Expert",
    category: "Dynamic",
    tools: ["Frida", "DexDump", "Medusa"],
    steps: [
      "شغل التطبيق وانتظر حتى يفك التشفير عن نفسه في الذاكرة.",
      "استخدم Frida Hook على 'DefineClass' أو 'OpenMemory'.",
      "قم بنسخ محتوى الذاكرة (Memory Region) التي تحتوي على سحر 'dex'.",
      "احفظ البيانات في ملف .dex جديد.",
      "افتح الملف الناتج في JADX للتحليل.",
    ],
    notes: "طريقة فعالة جداً ضد الـ Packers التجارية.",
  },
];
