export interface Tool {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: "Static" | "Dynamic" | "Network" | "Forensics" | "Root" | "Framework";
  level: "Beginner" | "Advanced" | "Expert";
  platform: string;
  website: string;
  author: string;
  stars: string;
  commands: string[];
  features: string[];
  useCases: string[];
}

export const TOOLS: Tool[] = [
  {
    id: "jadx",
    name: "JADX",
    tagline: "أقوى مفكك Java في العالم",
    description: "يفكّك ملفات DEX وAPK إلى كود Java/Kotlin مقروء بجودة استثنائية. يدعم GUI كاملة مع بحث متقدم وتحليل تبعيات.",
    category: "Static",
    level: "Beginner",
    platform: "Windows / macOS / Linux",
    website: "github.com/skylot/jadx",
    author: "skylot",
    stars: "43k+",
    commands: [
      "jadx app.apk -d output/",
      "jadx-gui app.apk",
      "jadx --deobf app.apk -d output/",
      "jadx -r app.apk -d output/",
    ],
    features: [
      "فك تشفير DEX إلى Java بدقة عالية",
      "واجهة رسومية متكاملة",
      "Deobfuscation تلقائي",
      "بحث في الكود بالكامل",
      "تصدير مشاريع Gradle",
    ],
    useCases: [
      "قراءة كود التطبيق المغلق",
      "فهم منطق التشفير والترخيص",
      "تحليل الـ Malware",
      "Bug Bounty على تطبيقات الأندرويد",
    ],
  },
  {
    id: "apktool",
    name: "APKTool",
    tagline: "فك وإعادة بناء APK بشكل كامل",
    description: "الأداة المعيارية لفك ملفات APK إلى Smali وموارد XML، وإعادة بنائها مع إمكانية تعديل الكود والموارد.",
    category: "Static",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "ibotpeaches.github.io/Apktool",
    author: "iBotPeaches",
    stars: "20k+",
    commands: [
      "apktool d app.apk -o output/",
      "apktool b output/ -o patched.apk",
      "apktool d app.apk -s -o output/",
      "apktool if framework.apk",
    ],
    features: [
      "فك APK إلى Smali قابل للتعديل",
      "إعادة البناء مع التعديلات",
      "دعم كامل لـ Resources",
      "Framework management",
    ],
    useCases: [
      "Smali Patching وتعديل السلوك",
      "تعديل الموارد والنصوص",
      "إزالة الإعلانات",
      "تجاوز الحماية",
    ],
  },
  {
    id: "frida",
    name: "Frida",
    tagline: "حقن JavaScript في أي عملية حية",
    description: "إطار instrumentation ديناميكي يمكّنك من حقن JavaScript في عمليات أندرويد/iOS مباشرة لمراقبة وتعديل السلوك في الوقت الفعلي.",
    category: "Dynamic",
    level: "Expert",
    platform: "Android / iOS / Windows / Linux",
    website: "frida.re",
    author: "Frida Team",
    stars: "16k+",
    commands: [
      "frida -U -f com.app.target -l script.js",
      "frida-ps -Ua",
      "frida-trace -U -i 'open' com.app",
      "frida-dump -U com.app.target",
      "frida -U com.app --codeshare user/script",
    ],
    features: [
      "حقن JavaScript في الوقت الفعلي",
      "Hook على أي دالة",
      "استخراج البيانات من الذاكرة",
      "Bypass الحماية الديناميكية",
      "Python API قوي",
    ],
    useCases: [
      "SSL Pinning Bypass",
      "Root Detection Bypass",
      "استخراج مفاتيح التشفير",
      "تحليل API calls",
    ],
  },
  {
    id: "ghidra",
    name: "Ghidra",
    tagline: "محطة NSA للهندسة العكسية",
    description: "إطار هندسة عكسية متكامل طوّرته وكالة NSA الأمريكية. يدعم ARM/x86/MIPS وتحليل native libraries بعمق استثنائي.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "ghidra-sre.org",
    author: "NSA",
    stars: "52k+",
    commands: [
      "ghidraRun",
      "analyzeHeadless . proj -import lib.so -postScript ExportScript.java",
    ],
    features: [
      "Disassembler + Decompiler متكامل",
      "دعم ARM/x86/MIPS/PowerPC",
      "تحليل Native Libraries (.so)",
      "Scripting بـ Java/Python",
      "تحليل جماعي Headless",
    ],
    useCases: [
      "تحليل Native Code في APK",
      "فهم خوارزميات التشفير المُدمجة",
      "Malware Analysis متقدم",
      "Vulnerability Research",
    ],
  },
  {
    id: "objection",
    name: "objection",
    tagline: "استكشاف التطبيق بدون Root",
    description: "إطار اختبار مبني على Frida يتيح استكشاف تطبيقات الأندرويد وiOS في الوقت الفعلي بدون الحاجة لـ Root.",
    category: "Dynamic",
    level: "Advanced",
    platform: "Android / iOS",
    website: "github.com/sensepost/objection",
    author: "SensePost",
    stars: "7k+",
    commands: [
      "objection -g com.app.target explore",
      "android sslpinning disable",
      "android root disable",
      "android hooking list classes",
      "android hooking watch class_method com.app.Auth.login",
    ],
    features: [
      "SSL Pinning Bypass بأمر واحد",
      "Root Detection Bypass",
      "عرض الـ Heap والكلاسات",
      "Hook على الدوال تلقائياً",
      "بدون Jailbreak/Root",
    ],
    useCases: [
      "اختبار تطبيقات الإنتاج بسرعة",
      "Bypass الحماية الأساسية",
      "استكشاف الكلاسات والدوال",
    ],
  },
  {
    id: "mobsf",
    name: "MobSF",
    tagline: "إطار أمان الجوال الشامل",
    description: "Mobile Security Framework — منصة متكاملة للتحليل الساكن والديناميكي وAPI تعمل عبر واجهة ويب احترافية.",
    category: "Forensics",
    level: "Beginner",
    platform: "Windows / macOS / Linux / Docker",
    website: "mobsf.github.io",
    author: "Ajinabraham",
    stars: "18k+",
    commands: [
      "docker pull opensecurity/mobile-security-framework-mobsf",
      "docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf",
      "python manage.py runserver",
    ],
    features: [
      "Static Analysis تلقائي شامل",
      "Dynamic Analysis مدمج",
      "تقارير PDF احترافية",
      "REST API للأتمتة",
      "كشف Malware والثغرات",
    ],
    useCases: [
      "تقييم سريع لأمن التطبيق",
      "Compliance Security Testing",
      "CI/CD Security Pipeline",
    ],
  },
  {
    id: "burpsuite",
    name: "Burp Suite",
    tagline: "معترض الحركة الاحترافي",
    description: "المنصة الأشهر لاعتراض وتحليل حركة HTTPS بين التطبيق والـ API، مع إمكانيات متقدمة للاختبار.",
    category: "Network",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "portswigger.net/burp",
    author: "PortSwigger",
    stars: "Industry Standard",
    commands: [
      "adb shell settings put global http_proxy 192.168.x.x:8080",
      "adb shell settings put global http_proxy :0",
    ],
    features: [
      "اعتراض HTTP/HTTPS",
      "Repeater و Scanner",
      "Intruder للـ Fuzzing",
      "دعم WebSocket",
      "Extensions بـ Java/Python",
    ],
    useCases: [
      "تحليل API communication",
      "اكتشاف ثغرات الـ Backend",
      "اختبار المصادقة والتفويض",
    ],
  },
  {
    id: "radare2",
    name: "Radare2",
    tagline: "إطار هندسة عكسية مفتوح المصدر",
    description: "إطار تحليل ثنائي قوي بواجهة سطر أوامر، يدعم عشرات المعماريات مع scripting بـ Python/JavaScript.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "radare.org",
    author: "Pancake",
    stars: "21k+",
    commands: [
      "r2 -A lib.so",
      "aaa && afl",
      "pdf @ main",
      "r2 -qc 'aaa;afl' lib.so",
      "r2frida -U -f com.app",
    ],
    features: [
      "Disassembler متعدد المعماريات",
      "Debugger مدمج",
      "r2frida للتحليل الديناميكي",
      "Scripting API قوي",
      "Binary patching",
    ],
    useCases: [
      "تحليل Native Libraries المعقدة",
      "Exploit Development",
      "CTF Challenges",
    ],
  },
  {
    id: "drozer",
    name: "Drozer",
    tagline: "اختبار مكونات أندرويد",
    description: "إطار متخصص في اختبار أمان مكونات أندرويد: Activities وServices وContent Providers وBroadcast Receivers.",
    category: "Dynamic",
    level: "Advanced",
    platform: "Android",
    website: "github.com/WithSecureLabs/drozer",
    author: "WithSecure Labs",
    stars: "3.5k+",
    commands: [
      "adb forward tcp:31415 tcp:31415",
      "drozer console connect",
      "run app.package.info -a com.app",
      "run app.activity.start --component com.app com.app.LoginActivity",
      "run scanner.provider.injection -a com.app",
    ],
    features: [
      "اختبار IPC components",
      "كشف Content Provider Injection",
      "Activity hijacking",
      "Intent fuzzing",
    ],
    useCases: [
      "اختبار exported components",
      "كشف ثغرات IPC",
      "Penetration Testing متخصص",
    ],
  },
  {
    id: "magisk",
    name: "Magisk",
    tagline: "Root الأندرويد بذكاء",
    description: "الحل الأكثر تقدماً لـ Root أجهزة أندرويد مع دعم Zygisk للـ Hooking على مستوى النظام وإخفاء الـ Root.",
    category: "Root",
    level: "Advanced",
    platform: "Android",
    website: "github.com/topjohnwu/Magisk",
    author: "topjohnwu",
    stars: "50k+",
    commands: [
      "adb push Magisk.apk /data/local/tmp/",
      "magisk --install-module module.zip",
      "magisk hide enable",
    ],
    features: [
      "Systemless Root",
      "Zygisk (Xposed-compatible)",
      "MagiskHide لإخفاء Root",
      "Module system متكامل",
      "SafetyNet bypass",
    ],
    useCases: [
      "تفعيل Root للاختبار",
      "تثبيت Frida Gadget",
      "Bypass SafetyNet/Play Integrity",
    ],
  },
  {
    id: "xposed",
    name: "Xposed / LSPosed",
    tagline: "Hook على مستوى ART",
    description: "إطار يتيح Hook على دوال أي تطبيق أندرويد عبر تعديل ART runtime بدون تعديل ملفات APK.",
    category: "Framework",
    level: "Expert",
    platform: "Android",
    website: "github.com/LSPosed/LSPosed",
    author: "LSPosed Team",
    stars: "20k+",
    commands: [
      "// في الـ Module",
      "XposedHelpers.findAndHookMethod(",
      "  'com.app.Auth', lpparam.classLoader,",
      "  'isLicensed', XC_MethodReplacement.returnConstant(true));",
    ],
    features: [
      "Hook أي دالة في أي تطبيق",
      "تعديل الـ return values",
      "مراقبة الـ method calls",
      "Persist بعد إعادة التشغيل",
    ],
    useCases: [
      "License bypass دائم",
      "تعديل سلوك التطبيق",
      "Privacy modules",
    ],
  },
  {
    id: "mitmproxy",
    name: "mitmproxy",
    tagline: "Proxy مفتوح المصدر بـ Python",
    description: "Proxy تفاعلي يعترض ويعدّل ويعيد تشغيل HTTP/HTTPS مع إمكانية scripting بـ Python.",
    category: "Network",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "mitmproxy.org",
    author: "mitmproxy team",
    stars: "38k+",
    commands: [
      "mitmproxy -p 8080",
      "mitmweb -p 8080",
      "mitmdump -p 8080 -s script.py",
      "mitmdump -p 8080 -w traffic.dump",
    ],
    features: [
      "Web UI تفاعلية",
      "Python scripting",
      "تسجيل وإعادة تشغيل الحركة",
      "Addon system",
    ],
    useCases: [
      "تحليل API بشكل آلي",
      "تعديل الاستجابات تلقائياً",
      "اختبار الأمان الآلي",
    ],
  },
  {
    id: "androguard",
    name: "AndroGuard",
    tagline: "تحليل APK بـ Python",
    description: "مكتبة Python قوية لتحليل ملفات APK وDEX برمجياً، مثالية للأتمتة وكشف الـ Malware.",
    category: "Forensics",
    level: "Advanced",
    platform: "Linux / macOS / Windows",
    website: "github.com/androguard/androguard",
    author: "androguard",
    stars: "5k+",
    commands: [
      "from androguard.core.apk import APK",
      "a = APK('app.apk')",
      "print(a.get_package())",
      "print(a.get_permissions())",
      "androlyze.py -s app.apk",
    ],
    features: [
      "Python API كامل",
      "تحليل Permissions و Components",
      "كشف المكتبات والتبعيات",
      "Control Flow Graph",
      "Similarity analysis",
    ],
    useCases: [
      "Malware detection مُؤتمت",
      "تحليل مجمّع لآلاف APKs",
      "أبحاث الأمان",
    ],
  },
  {
    id: "apkid",
    name: "APKiD",
    tagline: "كشف الحماية والتشفير",
    description: "يحدد بدقة نوع المُعبِّئ والمُشفِّر وأدوات الحماية المستخدمة في APK (ProGuard, DexGuard, Obfuscator, Packer).",
    category: "Forensics",
    level: "Beginner",
    platform: "Linux / macOS",
    website: "github.com/rednaga/APKiD",
    author: "rednaga",
    stars: "2k+",
    commands: [
      "apkid app.apk",
      "apkid -r app.apk",
      "apkid --json app.apk",
    ],
    features: [
      "كشف 300+ نوع حماية",
      "تحديد المُعبِّئ (Packer)",
      "كشف Anti-Tamper",
      "JSON output للأتمتة",
    ],
    useCases: [
      "معرفة نوع الحماية قبل البدء",
      "تصنيف Malware",
      "تقييم صعوبة الهندسة العكسية",
    ],
  },
  {
    id: "idapro",
    name: "IDA Pro 9",
    tagline: "المعيار الذهبي للتفكيك",
    description: "أشهر أداة hacking commercially في العالم من Hex-Rays. يدعم 100+ معمارية معالج ويوفر Decompiler فوري إلى C/C++ مع Plugin SDK بـ Python/IDC.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "hex-rays.com/ida-pro",
    author: "Hex-Rays",
    stars: "Commercial - Industry Standard",
    commands: [
      "idat64 -c -A -Sscript.idc app.so",
      "idat64 app.so",
      "idapython script.py",
    ],
    features: [
      "يدعم 100+ معمارية معالج",
      "Decompiler فوري إلى C/C++",
      "Plugin SDK بـ Python/IDC",
      "Interactive Disassembly",
      "Graph view متقدم",
    ],
    useCases: [
      "التحليل الجنائي للبرمجيات",
      "الهندسة العكسية للمكتبات الأصلية",
      "اكتشاف الثغرات الأمنية",
    ],
  },
  {
    id: "binaryninja",
    name: "Binary Ninja",
    tagline: "محلل ثنائي الجيل الجديد",
    description: "محلل ثنائي يوفر HLIL (High Level IL) - أعلى مستوى تجريد في العالم. يتميز بـ Python/Rust plugin API و Cloud collaboration features.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "binary.ninja",
    author: "Vector35",
    stars: "15k+",
    commands: [
      "binaryninja",
      "python script.py # using binaryninja API",
    ],
    features: [
      "HLIL (High Level IL) تجريد عالي",
      "Python/Rust plugin API",
      "Cloud collaboration features",
      "Modern UI/UX",
      "Automatic structure recovery",
    ],
    useCases: [
      "تطوير البرمجيات الخبيثة (لأغراض أمنية)",
      "تحليل الثغرات",
      "هندسة عكسية سريعة",
    ],
  },
  {
    id: "angr",
    name: "Angr",
    tagline: "محرك تحليل رمزي",
    description: "محرك تحليل رمزي (Symbolic execution engine) يحل CTF challenges تلقائياً ويقوم بـ Automated vulnerability discovery.",
    category: "Static",
    level: "Expert",
    platform: "Linux / macOS / Windows",
    website: "angr.io",
    author: "University of California, Santa Barbara",
    stars: "7k+",
    commands: [
      "import angr; p = angr.Project('lib.so'); sim = p.factory.simgr()",
    ],
    features: [
      "Symbolic execution engine",
      "يحل CTF challenges تلقائياً",
      "Automated vulnerability discovery",
      "Control flow graph recovery",
      "Data-flow analysis",
    ],
    useCases: [
      "اكتشاف مسارات التنفيذ المخفية",
      "حل تحديات CTF المعقدة",
      "أتمتة اكتشاف الثغرات",
    ],
  },
  {
    id: "apkleaks",
    name: "APKLeaks",
    tagline: "كشف المعلومات المسرّبة",
    description: "يكشف URLs, IPs, API keys, secrets من APK باستخدام patterns قابلة للتخصيص.",
    category: "Forensics",
    level: "Beginner",
    platform: "Linux / macOS / Windows",
    website: "github.com/dwisiswant0/apkleaks",
    author: "dwisiswant0",
    stars: "4k+",
    commands: [
      "apkleaks -f app.apk",
      "apkleaks -f app.apk -o results.json",
    ],
    features: [
      "كشف API keys و Secrets",
      "كشف URLs و IPs",
      "Patterns قابلة للتخصيص",
      "دعم التقارير بصيغة JSON",
    ],
    useCases: [
      "بحث عن تسريبات البيانات",
      "فحص أولي لأمن التطبيق",
      "Bug Bounty",
    ],
  },
  {
    id: "bytecodeviewer",
    name: "Bytecode Viewer",
    tagline: "6 مفككات في واجهة واحدة",
    description: "يعرض JADX + Procyon + CFR + Fernflower + Krakatau + Smali معاً لمقارنة نتائج المفككات المختلفة.",
    category: "Static",
    level: "Beginner",
    platform: "Windows / macOS / Linux",
    website: "github.com/Konloch/bytecode-viewer",
    author: "Konloch",
    stars: "15k+",
    commands: [
      "java -jar Bytecode-Viewer.jar",
    ],
    features: [
      "يجمع 6 مفككات Java",
      "مقارنة النتائج جنباً إلى جنب",
      "واجهة رسومية سهلة",
      "دعم Android APKs",
    ],
    useCases: [
      "تحليل الكود عند فشل JADX",
      "فهم الاختلافات بين المفككات",
      "التعليم والتدريب",
    ],
  },
  {
    id: "house",
    name: "House",
    tagline: "Frida GUI تفاعلي",
    description: "واجهة ويب لـ Frida تتيح اختبار API hooks بسهولة ومتكاملة مع objection.",
    category: "Dynamic",
    level: "Advanced",
    platform: "Linux / macOS",
    website: "github.com/nccgroup/house",
    author: "NCCGroup",
    stars: "1.5k+",
    commands: [
      "python3 house.py",
    ],
    features: [
      "واجهة ويب لـ Frida",
      "اختبار API hooks بسهولة",
      "متكامل مع objection",
      "توليد scripts Frida تلقائياً",
    ],
    useCases: [
      "تبسيط استخدام Frida",
      "مراقبة API calls بصرياً",
      "تطوير scripts Hooking سريعة",
    ],
  },
  {
    id: "sslkillswitch3",
    name: "SSL Kill Switch 3",
    tagline: "iOS SSL Pinning Bypass",
    description: "يوقف SSL Pinning على iOS بضغطة واحدة، يعمل مع كل frameworks iOS.",
    category: "Dynamic",
    level: "Advanced",
    platform: "iOS (Jailbreak)",
    website: "github.com/evilpenguin/SSLKillSwitch3",
    author: "EvilPenguin",
    stars: "2k+",
    commands: [
      "// يتم تفعيله من الإعدادات في iOS",
    ],
    features: [
      "إبطال SSL Pinning بضغطة واحدة",
      "دعم كامل لـ iOS 15+",
      "يعمل مع NSURLSession و NSURLConnection",
      "يدعم تطبيقات الطرف الثالث",
    ],
    useCases: [
      "تحليل حركة المرور المشفرة على iOS",
      "اختبار الأمان لتطبيقات آيفون",
    ],
  },
  {
    id: "jadxai",
    name: "Jadx-AI",
    tagline: "JADX مع ذكاء اصطناعي",
    description: "يضيف AI analysis لنتائج JADX، يشرح الكود تلقائياً ويكتشف الـ patterns الأمنية.",
    category: "Static",
    level: "Beginner",
    platform: "Windows / macOS / Linux",
    website: "github.com/LaurieWired/JADXecute",
    author: "LaurieWired",
    stars: "2k+",
    commands: [
      "jadx-gui --ai",
    ],
    features: [
      "شرح الكود بالذكاء الاصطناعي",
      "اكتشاف الـ patterns الأمنية",
      "تحليل وظائف الدوال المعقدة",
      "تكامل مع OpenAI/Ollama",
    ],
    useCases: [
      "فهم سريع للكود المعقد",
      "تحديد مواضع الثغرات بسرعة",
      "أتمتة شرح منطق التطبيق",
    ],
  },
  {
    id: "binaryen",
    name: "Binaryen / wasm-opt",
    tagline: "أداة WebAssembly reversing",
    description: "مجموعة أدوات ومكتبة بنية تحتية لـ WebAssembly. تتضمن wasm-opt لتحليل وتحسين وتعديل ملفات .wasm المستخدمة في تطبيقات hybrid.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "github.com/WebAssembly/binaryen",
    author: "WebAssembly",
    stars: "8k+",
    commands: [
      "wasm-opt input.wasm -o output.wasm -O3",
      "wasm-dis input.wasm -o output.wat",
      "wasm-as input.wat -o output.wasm",
    ],
    features: [
      "تحليل وتحسين ملفات WASM",
      "تحويل بين تنسيق Binary و Text",
      "إطار عمل قوي للمترجمات",
      "دعم كامل لكل ميزات WebAssembly",
    ],
    useCases: [
      "تحليل WebAssembly في تطبيقات Hybrid",
      "تحسين أداء كود WASM",
      "تعديل سلوك الوحدات البرمجية WASM",
    ],
  },
  {
    id: "cutter",
    name: "Cutter",
    tagline: "واجهة رسومية قوية لـ Radare2",
    description: "واجهة رسومية متطورة وحديثة مبنية على Radare2. تهدف لتوفير تجربة مستخدم ممتازة مع قوة r2 الهائلة في التحليل.",
    category: "Static",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "cutter.re",
    author: "Cutter Team",
    stars: "8k+",
    commands: [
      "cutter /path/to/binary",
    ],
    features: [
      "تكامل كامل مع Radare2",
      "دعم Jupyter notebooks",
      "Decompiler مدمج (r2dec + r2ghidra)",
      "Graph view تفاعلي",
      "محاكي Emulation مدمج",
    ],
    useCases: [
      "تحليل البرمجيات الخبيثة بصرياً",
      "الهندسة العكسية للمكتبات الأصلية",
      "تسهيل استخدام Radare2",
    ],
  },
  {
    id: "nuclei",
    name: "Nuclei",
    tagline: "محرك فحص الثغرات الآلي",
    description: "أداة قوية لإرسال الطلبات بناءً على قوالب (templates) بسيطة تعتمد على YAML، مما يسمح بفحص آلاف الأهداف بسرعة ودقة.",
    category: "Network",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "nuclei.projectdiscovery.io",
    author: "ProjectDiscovery",
    stars: "22k+",
    commands: [
      "nuclei -u https://api.target.com",
      "nuclei -list urls.txt -t cves/ -o results.txt",
      "nuclei -u https://api.target.com -t exposures/tokens/",
    ],
    features: [
      "9000+ template جاهز لفحص APIs",
      "دعم بروتوكولات متعددة (HTTP, TCP, DNS)",
      "سرعة فائقة في الفحص",
      "تخصيص كامل للقوالب",
    ],
    useCases: [
      "فحص API endpoints المستخرجة",
      "اكتشاف الثغرات المعروفة تلقائياً",
      "مراقبة الهجوم السحابي",
    ],
  },
  {
    id: "semgrep",
    name: "Semgrep",
    tagline: "تحليل كود ثابت متقدم",
    description: "أداة تحليل ساكن (SAST) سريعة ومفتوحة المصدر للبحث في الكود المصدري واكتشاف الأخطاء البرمجية ونقاط الضعف.",
    category: "Static",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "semgrep.dev",
    author: "Semgrep Inc",
    stars: "10k+",
    commands: [
      "semgrep --config=p/android app/",
      "semgrep --config=p/java app/",
      "semgrep --config=auto",
    ],
    features: [
      "يكتشف patterns الثغرات في الكود",
      "دعم 30+ لغة برمجة",
      "Rules جاهزة لـ Android security",
      "تكامل سهل مع CI/CD",
    ],
    useCases: [
      "مراجعة الكود المصدري (Code Review)",
      "تحديد أنماط البرمجة غير الآمنة",
      "أتمتة اكتشاف الثغرات في المشاريع الكبيرة",
    ],
  },
  {
    id: "pwndbg",
    name: "GDB + pwndbg",
    tagline: "مُنقِّح GNU المحسّن",
    description: "توسعة قوية لـ GDB تجعله أداة استثنائية لتحليل البرمجيات وتطوير الثغرات، مع واجهة محسنة لعرض حالة الذاكرة والمسجلات.",
    category: "Dynamic",
    level: "Expert",
    platform: "Linux",
    website: "github.com/pwndbg/pwndbg",
    author: "pwndbg team",
    stars: "7k+",
    commands: [
      "gdb -q ./binary",
      "source pwndbg/gdbinit.py",
      "context",
      "heap",
      "ropgadget",
    ],
    features: [
      "تحليل crashes وexploits في native code",
      "Heap analysis متقدم",
      "ROP chain detection",
      "عرض مرئي للذاكرة والـ Stack",
    ],
    useCases: [
      "تطوير الـ Exploits",
      "تحليل Native crashes في أندرويد",
      "تجاوز حماية الذاكرة (ASLR, NX)",
    ],
  },
  {
    id: "volatility",
    name: "Volatility 3",
    tagline: "تحليل الذاكرة",
    description: "الإطار المعياري العالمي لتحليل ذاكرة الوصول العشوائي (RAM) واستخراج الأدلة الرقمية من الأجهزة المخترقة.",
    category: "Forensics",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "volatilityfoundation.org",
    author: "Volatility Foundation",
    stars: "7k+",
    commands: [
      "python3 vol.py -f memory.dump android.pslist",
      "python3 vol.py -f memory.dump android.dumpfiles",
      "python3 vol.py -f memory.dump android.callbacks",
    ],
    features: [
      "استخراج مفاتيح التشفير من RAM dumps",
      "تحليل عمليات Android في الذاكرة",
      "كشف الـ Rootkits والعمليات المخفية",
      "دعم كامل لنواة Linux و Android",
    ],
    useCases: [
      "التحليل الجنائي الرقمي (Digital Forensics)",
      "كشف التهديدات المتقدمة",
      "استعادة البيانات من الذاكرة الحية",
    ],
  },
  {
    id: "imhex",
    name: "ImHex",
    tagline: "محرر Hex متقدم للمختصين",
    description: "محرر Hex حديث ومفتوح المصدر مصمم للمهندسين العكسيين. يتميز بنظام patterns قوي جداً لتحليل البيانات وتنسيقات الملفات المعقدة.",
    category: "Forensics",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "github.com/WerWolv/ImHex",
    author: "WerWolv",
    stars: "35k+",
    commands: [
      "imhex /path/to/file",
    ],
    features: [
      "نظام Custom Patterns لتحليل البيانات",
      "يدعم ملفات ضخمة جداً",
      "Data Inspector متكامل",
      "Visualizer للبيانات والـ Entropy",
      "Scripting بـ Python",
    ],
    useCases: [
      "تحليل تنسيقات ملفات غير معروفة",
      "استخراج البيانات من Binary dumps",
      "تحليل Firmware الأجهزة",
    ],
  },
  {
    id: "jeb-decompiler",
    name: "JEB Decompiler",
    tagline: "المفكك الاحترافي لـ Android",
    description: "أداة هندسة عكسية تجارية قوية جداً متخصصة في Android. توفر فك تشفير DEX و Native code بمستوى احترافي وتتفوق في التعامل مع obfuscation المعقد.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "pnfsoftware.com",
    author: "PNF Software",
    stars: "Commercial Standard",
    commands: [
      "jeb -c --file=app.apk",
      "jeb -c --python=myscript.py",
    ],
    features: [
      "أفضل Decompiler لـ DEX و Smali",
      "دعم كامل لـ WebAssembly و Native code",
      "Interactive graph analysis",
      "API متقدم للأتمتة والـ Scripting",
      "قدرات De-obfuscation متفوقة",
    ],
    useCases: [
      "تحليل التطبيقات المصرفية المحمية",
      "الهندسة العكسية لـ Malware معقد",
      "التحليل الاحترافي للشركات",
    ],
  },
  {
    id: "diaphora",
    name: "Diaphora",
    tagline: "أداة مقارنة الـ Binary الأكثر تقدماً",
    description: "أداة (Diffing) مفتوحة المصدر تعمل كإضافة لـ IDA Pro و Ghidra و Binary Ninja. تستخدم لمقارنة ملفين ثنائيين وتحديد الاختلافات بدقة.",
    category: "Static",
    level: "Expert",
    platform: "Cross-platform (Python)",
    website: "github.com/joxeankoret/diaphora",
    author: "Joxean Koret",
    stars: "3.5k+",
    commands: [
      "python diaphora.py --export database.db binary.so",
      "python diaphora.py --diff db1.db db2.db",
    ],
    features: [
      "مقارنة الوظائف بناءً على الـ Graphs",
      "دعم IDA Pro و Ghidra و Binary Ninja",
      "تصدير النتائج لقواعد بيانات SQLite",
      "كشف التغييرات في كود الـ Native",
      "نظام heuristics متطور للمطابقة",
    ],
    useCases: [
      "تحليل التغييرات الأمنية (Patch Diffing)",
      "نقل الـ symbols بين نسخ التطبيقات",
      "كشف الكود المسروق أو المستنسخ",
    ],
  },
  {
    id: "r2frida",
    name: "r2frida",
    tagline: "دمج قوة Radare2 مع Frida",
    description: "إضافة لـ Radare2 تتيح لك استخدام أوامر r2 للتحقق والتحكم في العمليات الحية عبر Frida. تجمع بين التحليل الساكن والديناميكي في مكان واحد.",
    category: "Dynamic",
    level: "Expert",
    platform: "Android / iOS / Desktop",
    website: "github.com/nowsecure/r2frida",
    author: "NowSecure / Pancake",
    stars: "3k+",
    commands: [
      "r2 frida://usb/com.app.target",
      ":dt",
      ":dm",
      ":dc",
      ":dxc open",
    ],
    features: [
      "استخدام أوامر Radare2 على عمليات حية",
      "تتبع الـ API calls في الوقت الفعلي",
      "قراءة وكتابة الذاكرة مباشرة",
      "Hooking ديناميكي بدون مغادرة r2 shell",
      "دعم كامل لـ iOS و Android",
    ],
    useCases: [
      "تحليل الـ Native Hooking المعقد",
      "تعديل سلوك التطبيق أثناء التشغيل",
      "البحث عن مفاتيح التشفير في الذاكرة",
    ],
  },
  {
    id: "apkeditor",
    name: "APKEditor",
    tagline: "تعديل APK بسهولة وسرعة",
    description: "أداة حديثة وفعالة لتعديل ملفات APK و Split APKs. تتيح دمج ملفات الـ Resources وتغيير إعدادات التطبيق دون الحاجة لفك التشفير الكامل.",
    category: "Static",
    level: "Advanced",
    platform: "Android / Windows / Linux",
    website: "github.com/REAndroid/APKEditor",
    author: "REAndroid",
    stars: "1.5k+",
    commands: [
      "apkeditor d -i app.apk -o output/",
      "apkeditor b -i output/ -o new.apk",
      "apkeditor m -i split_apks/ -o merged.apk",
    ],
    features: [
      "دعم كامل لـ Split APKs (App Bundles)",
      "دمج ملفات الترجمة والموارد",
      "سرعة عالية في إعادة البناء",
      "إصلاح ملفات الـ Resources التالفة",
      "واجهة سطر أوامر بسيطة",
    ],
    useCases: [
      "تحويل Split APKs إلى ملف APK واحد",
      "تعديل الـ AndroidManifest بسرعة",
      "إضافة مكتبات Hooking للتطبيقات",
    ],
  },
  {
    id: "quark-engine",
    name: "Quark-Engine",
    tagline: "تحليل سلوك التطبيق بالذكاء الاصطناعي",
    description: "محرك تحليل مالوير لنظام أندرويد يركز على سلوك التطبيق بدلاً من الأكواد. يقوم بتحويل ملفات DEX إلى قواعد منطقية للكشف عن الأنشطة المشبوهة.",
    category: "Forensics",
    level: "Advanced",
    platform: "Linux / macOS / Windows",
    website: "quark-engine.org",
    author: "Quark-Engine Team",
    stars: "2.5k+",
    commands: [
      "quark -a app.apk",
      "quark -a app.apk -s",
      "quark -a app.apk -r rules/",
    ],
    features: [
      "كشف السلوكيات الضارة بناءً على القواعد",
      "توليد تقارير شاملة عن نشاط التطبيق",
      "نظام تقييم مخاطر (Risk Scoring)",
      "سهولة إضافة قواعد كشف جديدة",
      "تكامل مع أدوات التحليل الأخرى",
    ],
    useCases: [
      "تصنيف الـ Malware تلقائياً",
      "تحليل التهديدات المستهدفة",
      "فحص أمان التطبيقات في المتاجر",
    ],
  },
  {
    id: "jnitrace",
    name: "Jnitrace",
    tagline: "تتبع استدعاءات JNI الأصلية",
    description: "أداة مبنية على Frida تتيح تتبع جميع استدعاءات JNI (Java Native Interface) بين كود Java وكود C/C++. مفيدة جداً لفهم العمليات التي تتم في المكتبات الأصلية.",
    category: "Dynamic",
    level: "Expert",
    platform: "Android",
    website: "github.com/chame1eon/jnitrace",
    author: "chame1eon",
    stars: "2k+",
    commands: [
      "jnitrace -l libnative.so com.app.target",
      "jnitrace -m attach com.app.target",
    ],
    features: [
      "عرض استدعاءات الدوال الأصلية بوضوح",
      "تتبع تحويل البيانات بين Java و Native",
      "تحديد المعاملات والقيم المسترجعة",
      "دعم تصفية (Filtering) للمكتبات المحددة",
      "إخراج النتائج بتنسيق JSON",
    ],
    useCases: [
      "تحليل كيفية عمل حماية الـ Native",
      "فهم خوارزميات التشفير في ملفات .so",
      "اكتشاف الثغرات في طبقة JNI",
    ],
  },
];
