export interface Tool {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: "Static" | "Dynamic" | "Network" | "Forensics" | "Root" | "Framework";
  level: "Beginner" | "Advanced" | "Expert";
  platform: string;
  website: string;
  author: string;
  stars: string;
  commands: string[];
  features: string[];
  useCases: string[];
}

export const TOOLS: Tool[] = [
  {
    id: "jadx",
    name: "JADX",
    tagline: "أقوى مفكك Java في العالم",
    description: "يفكّك ملفات DEX وAPK إلى كود Java/Kotlin مقروء بجودة استثنائية. يدعم GUI كاملة مع بحث متقدم وتحليل تبعيات.",
    category: "Static",
    level: "Beginner",
    platform: "Windows / macOS / Linux",
    website: "github.com/skylot/jadx",
    author: "skylot",
    stars: "43k+",
    commands: [
      "jadx app.apk -d output/",
      "jadx-gui app.apk",
      "jadx --deobf app.apk -d output/",
      "jadx -r app.apk -d output/",
    ],
    features: [
      "فك تشفير DEX إلى Java بدقة عالية",
      "واجهة رسومية متكاملة",
      "Deobfuscation تلقائي",
      "بحث في الكود بالكامل",
      "تصدير مشاريع Gradle",
    ],
    useCases: [
      "قراءة كود التطبيق المغلق",
      "فهم منطق التشفير والترخيص",
      "تحليل الـ Malware",
      "Bug Bounty على تطبيقات الأندرويد",
    ],
  },
  {
    id: "apktool",
    name: "APKTool",
    tagline: "فك وإعادة بناء APK بشكل كامل",
    description: "الأداة المعيارية لفك ملفات APK إلى Smali وموارد XML، وإعادة بنائها مع إمكانية تعديل الكود والموارد.",
    category: "Static",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "ibotpeaches.github.io/Apktool",
    author: "iBotPeaches",
    stars: "20k+",
    commands: [
      "apktool d app.apk -o output/",
      "apktool b output/ -o patched.apk",
      "apktool d app.apk -s -o output/",
      "apktool if framework.apk",
    ],
    features: [
      "فك APK إلى Smali قابل للتعديل",
      "إعادة البناء مع التعديلات",
      "دعم كامل لـ Resources",
      "Framework management",
    ],
    useCases: [
      "Smali Patching وتعديل السلوك",
      "تعديل الموارد والنصوص",
      "إزالة الإعلانات",
      "تجاوز الحماية",
    ],
  },
  {
    id: "frida",
    name: "Frida",
    tagline: "حقن JavaScript في أي عملية حية",
    description: "إطار instrumentation ديناميكي يمكّنك من حقن JavaScript في عمليات أندرويد/iOS مباشرة لمراقبة وتعديل السلوك في الوقت الفعلي.",
    category: "Dynamic",
    level: "Expert",
    platform: "Android / iOS / Windows / Linux",
    website: "frida.re",
    author: "Frida Team",
    stars: "16k+",
    commands: [
      "frida -U -f com.app.target -l script.js",
      "frida-ps -Ua",
      "frida-trace -U -i 'open' com.app",
      "frida-dump -U com.app.target",
      "frida -U com.app --codeshare user/script",
    ],
    features: [
      "حقن JavaScript في الوقت الفعلي",
      "Hook على أي دالة",
      "استخراج البيانات من الذاكرة",
      "Bypass الحماية الديناميكية",
      "Python API قوي",
    ],
    useCases: [
      "SSL Pinning Bypass",
      "Root Detection Bypass",
      "استخراج مفاتيح التشفير",
      "تحليل API calls",
    ],
  },
  {
    id: "ghidra",
    name: "Ghidra",
    tagline: "محطة NSA للهندسة العكسية",
    description: "إطار هندسة عكسية متكامل طوّرته وكالة NSA الأمريكية. يدعم ARM/x86/MIPS وتحليل native libraries بعمق استثنائي.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "ghidra-sre.org",
    author: "NSA",
    stars: "52k+",
    commands: [
      "ghidraRun",
      "analyzeHeadless . proj -import lib.so -postScript ExportScript.java",
    ],
    features: [
      "Disassembler + Decompiler متكامل",
      "دعم ARM/x86/MIPS/PowerPC",
      "تحليل Native Libraries (.so)",
      "Scripting بـ Java/Python",
      "تحليل جماعي Headless",
    ],
    useCases: [
      "تحليل Native Code في APK",
      "فهم خوارزميات التشفير المُدمجة",
      "Malware Analysis متقدم",
      "Vulnerability Research",
    ],
  },
  {
    id: "objection",
    name: "objection",
    tagline: "استكشاف التطبيق بدون Root",
    description: "إطار اختبار مبني على Frida يتيح استكشاف تطبيقات الأندرويد وiOS في الوقت الفعلي بدون الحاجة لـ Root.",
    category: "Dynamic",
    level: "Advanced",
    platform: "Android / iOS",
    website: "github.com/sensepost/objection",
    author: "SensePost",
    stars: "7k+",
    commands: [
      "objection -g com.app.target explore",
      "android sslpinning disable",
      "android root disable",
      "android hooking list classes",
      "android hooking watch class_method com.app.Auth.login",
    ],
    features: [
      "SSL Pinning Bypass بأمر واحد",
      "Root Detection Bypass",
      "عرض الـ Heap والكلاسات",
      "Hook على الدوال تلقائياً",
      "بدون Jailbreak/Root",
    ],
    useCases: [
      "اختبار تطبيقات الإنتاج بسرعة",
      "Bypass الحماية الأساسية",
      "استكشاف الكلاسات والدوال",
    ],
  },
  {
    id: "mobsf",
    name: "MobSF",
    tagline: "إطار أمان الجوال الشامل",
    description: "Mobile Security Framework — منصة متكاملة للتحليل الساكن والديناميكي وAPI تعمل عبر واجهة ويب احترافية.",
    category: "Forensics",
    level: "Beginner",
    platform: "Windows / macOS / Linux / Docker",
    website: "mobsf.github.io",
    author: "Ajinabraham",
    stars: "18k+",
    commands: [
      "docker pull opensecurity/mobile-security-framework-mobsf",
      "docker run -it -p 8000:8000 opensecurity/mobile-security-framework-mobsf",
      "python manage.py runserver",
    ],
    features: [
      "Static Analysis تلقائي شامل",
      "Dynamic Analysis مدمج",
      "تقارير PDF احترافية",
      "REST API للأتمتة",
      "كشف Malware والثغرات",
    ],
    useCases: [
      "تقييم سريع لأمن التطبيق",
      "Compliance Security Testing",
      "CI/CD Security Pipeline",
    ],
  },
  {
    id: "burpsuite",
    name: "Burp Suite",
    tagline: "معترض الحركة الاحترافي",
    description: "المنصة الأشهر لاعتراض وتحليل حركة HTTPS بين التطبيق والـ API، مع إمكانيات متقدمة للاختبار.",
    category: "Network",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "portswigger.net/burp",
    author: "PortSwigger",
    stars: "Industry Standard",
    commands: [
      "adb shell settings put global http_proxy 192.168.x.x:8080",
      "adb shell settings put global http_proxy :0",
    ],
    features: [
      "اعتراض HTTP/HTTPS",
      "Repeater و Scanner",
      "Intruder للـ Fuzzing",
      "دعم WebSocket",
      "Extensions بـ Java/Python",
    ],
    useCases: [
      "تحليل API communication",
      "اكتشاف ثغرات الـ Backend",
      "اختبار المصادقة والتفويض",
    ],
  },
  {
    id: "radare2",
    name: "Radare2",
    tagline: "إطار هندسة عكسية مفتوح المصدر",
    description: "إطار تحليل ثنائي قوي بواجهة سطر أوامر، يدعم عشرات المعماريات مع scripting بـ Python/JavaScript.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "radare.org",
    author: "Pancake",
    stars: "21k+",
    commands: [
      "r2 -A lib.so",
      "aaa && afl",
      "pdf @ main",
      "r2 -qc 'aaa;afl' lib.so",
      "r2frida -U -f com.app",
    ],
    features: [
      "Disassembler متعدد المعماريات",
      "Debugger مدمج",
      "r2frida للتحليل الديناميكي",
      "Scripting API قوي",
      "Binary patching",
    ],
    useCases: [
      "تحليل Native Libraries المعقدة",
      "Exploit Development",
      "CTF Challenges",
    ],
  },
  {
    id: "drozer",
    name: "Drozer",
    tagline: "اختبار مكونات أندرويد",
    description: "إطار متخصص في اختبار أمان مكونات أندرويد: Activities وServices وContent Providers وBroadcast Receivers.",
    category: "Dynamic",
    level: "Advanced",
    platform: "Android",
    website: "github.com/WithSecureLabs/drozer",
    author: "WithSecure Labs",
    stars: "3.5k+",
    commands: [
      "adb forward tcp:31415 tcp:31415",
      "drozer console connect",
      "run app.package.info -a com.app",
      "run app.activity.start --component com.app com.app.LoginActivity",
      "run scanner.provider.injection -a com.app",
    ],
    features: [
      "اختبار IPC components",
      "كشف Content Provider Injection",
      "Activity hijacking",
      "Intent fuzzing",
    ],
    useCases: [
      "اختبار exported components",
      "كشف ثغرات IPC",
      "Penetration Testing متخصص",
    ],
  },
  {
    id: "magisk",
    name: "Magisk",
    tagline: "Root الأندرويد بذكاء",
    description: "الحل الأكثر تقدماً لـ Root أجهزة أندرويد مع دعم Zygisk للـ Hooking على مستوى النظام وإخفاء الـ Root.",
    category: "Root",
    level: "Advanced",
    platform: "Android",
    website: "github.com/topjohnwu/Magisk",
    author: "topjohnwu",
    stars: "50k+",
    commands: [
      "adb push Magisk.apk /data/local/tmp/",
      "magisk --install-module module.zip",
      "magisk hide enable",
    ],
    features: [
      "Systemless Root",
      "Zygisk (Xposed-compatible)",
      "MagiskHide لإخفاء Root",
      "Module system متكامل",
      "SafetyNet bypass",
    ],
    useCases: [
      "تفعيل Root للاختبار",
      "تثبيت Frida Gadget",
      "Bypass SafetyNet/Play Integrity",
    ],
  },
  {
    id: "xposed",
    name: "Xposed / LSPosed",
    tagline: "Hook على مستوى ART",
    description: "إطار يتيح Hook على دوال أي تطبيق أندرويد عبر تعديل ART runtime بدون تعديل ملفات APK.",
    category: "Framework",
    level: "Expert",
    platform: "Android",
    website: "github.com/LSPosed/LSPosed",
    author: "LSPosed Team",
    stars: "20k+",
    commands: [
      "// في الـ Module",
      "XposedHelpers.findAndHookMethod(",
      "  'com.app.Auth', lpparam.classLoader,",
      "  'isLicensed', XC_MethodReplacement.returnConstant(true));",
    ],
    features: [
      "Hook أي دالة في أي تطبيق",
      "تعديل الـ return values",
      "مراقبة الـ method calls",
      "Persist بعد إعادة التشغيل",
    ],
    useCases: [
      "License bypass دائم",
      "تعديل سلوك التطبيق",
      "Privacy modules",
    ],
  },
  {
    id: "mitmproxy",
    name: "mitmproxy",
    tagline: "Proxy مفتوح المصدر بـ Python",
    description: "Proxy تفاعلي يعترض ويعدّل ويعيد تشغيل HTTP/HTTPS مع إمكانية scripting بـ Python.",
    category: "Network",
    level: "Advanced",
    platform: "Windows / macOS / Linux",
    website: "mitmproxy.org",
    author: "mitmproxy team",
    stars: "38k+",
    commands: [
      "mitmproxy -p 8080",
      "mitmweb -p 8080",
      "mitmdump -p 8080 -s script.py",
      "mitmdump -p 8080 -w traffic.dump",
    ],
    features: [
      "Web UI تفاعلية",
      "Python scripting",
      "تسجيل وإعادة تشغيل الحركة",
      "Addon system",
    ],
    useCases: [
      "تحليل API بشكل آلي",
      "تعديل الاستجابات تلقائياً",
      "اختبار الأمان الآلي",
    ],
  },
  {
    id: "androguard",
    name: "AndroGuard",
    tagline: "تحليل APK بـ Python",
    description: "مكتبة Python قوية لتحليل ملفات APK وDEX برمجياً، مثالية للأتمتة وكشف الـ Malware.",
    category: "Forensics",
    level: "Advanced",
    platform: "Linux / macOS / Windows",
    website: "github.com/androguard/androguard",
    author: "androguard",
    stars: "5k+",
    commands: [
      "from androguard.core.apk import APK",
      "a = APK('app.apk')",
      "print(a.get_package())",
      "print(a.get_permissions())",
      "androlyze.py -s app.apk",
    ],
    features: [
      "Python API كامل",
      "تحليل Permissions و Components",
      "كشف المكتبات والتبعيات",
      "Control Flow Graph",
      "Similarity analysis",
    ],
    useCases: [
      "Malware detection مُؤتمت",
      "تحليل مجمّع لآلاف APKs",
      "أبحاث الأمان",
    ],
  },
  {
    id: "apkid",
    name: "APKiD",
    tagline: "كشف الحماية والتشفير",
    description: "يحدد بدقة نوع المُعبِّئ والمُشفِّر وأدوات الحماية المستخدمة في APK (ProGuard, DexGuard, Obfuscator, Packer).",
    category: "Forensics",
    level: "Beginner",
    platform: "Linux / macOS",
    website: "github.com/rednaga/APKiD",
    author: "rednaga",
    stars: "2k+",
    commands: [
      "apkid app.apk",
      "apkid -r app.apk",
      "apkid --json app.apk",
    ],
    features: [
      "كشف 300+ نوع حماية",
      "تحديد المُعبِّئ (Packer)",
      "كشف Anti-Tamper",
      "JSON output للأتمتة",
    ],
    useCases: [
      "معرفة نوع الحماية قبل البدء",
      "تصنيف Malware",
      "تقييم صعوبة الهندسة العكسية",
    ],
  },
  {
    id: "idapro",
    name: "IDA Pro 9",
    tagline: "المعيار الذهبي للتفكيك",
    description: "أشهر أداة hacking commercially في العالم من Hex-Rays. يدعم 100+ معمارية معالج ويوفر Decompiler فوري إلى C/C++ مع Plugin SDK بـ Python/IDC.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "hex-rays.com/ida-pro",
    author: "Hex-Rays",
    stars: "Commercial - Industry Standard",
    commands: [
      "idat64 -c -A -Sscript.idc app.so",
      "idat64 app.so",
      "idapython script.py",
    ],
    features: [
      "يدعم 100+ معمارية معالج",
      "Decompiler فوري إلى C/C++",
      "Plugin SDK بـ Python/IDC",
      "Interactive Disassembly",
      "Graph view متقدم",
    ],
    useCases: [
      "التحليل الجنائي للبرمجيات",
      "الهندسة العكسية للمكتبات الأصلية",
      "اكتشاف الثغرات الأمنية",
    ],
  },
  {
    id: "binaryninja",
    name: "Binary Ninja",
    tagline: "محلل ثنائي الجيل الجديد",
    description: "محلل ثنائي يوفر HLIL (High Level IL) - أعلى مستوى تجريد في العالم. يتميز بـ Python/Rust plugin API و Cloud collaboration features.",
    category: "Static",
    level: "Expert",
    platform: "Windows / macOS / Linux",
    website: "binary.ninja",
    author: "Vector35",
    stars: "15k+",
    commands: [
      "binaryninja",
      "python script.py # using binaryninja API",
    ],
    features: [
      "HLIL (High Level IL) تجريد عالي",
      "Python/Rust plugin API",
      "Cloud collaboration features",
      "Modern UI/UX",
      "Automatic structure recovery",
    ],
    useCases: [
      "تطوير البرمجيات الخبيثة (لأغراض أمنية)",
      "تحليل الثغرات",
      "هندسة عكسية سريعة",
    ],
  },
  {
    id: "angr",
    name: "Angr",
    tagline: "محرك تحليل رمزي",
    description: "محرك تحليل رمزي (Symbolic execution engine) يحل CTF challenges تلقائياً ويقوم بـ Automated vulnerability discovery.",
    category: "Static",
    level: "Expert",
    platform: "Linux / macOS / Windows",
    website: "angr.io",
    author: "University of California, Santa Barbara",
    stars: "7k+",
    commands: [
      "import angr; p = angr.Project('lib.so'); sim = p.factory.simgr()",
    ],
    features: [
      "Symbolic execution engine",
      "يحل CTF challenges تلقائياً",
      "Automated vulnerability discovery",
      "Control flow graph recovery",
      "Data-flow analysis",
    ],
    useCases: [
      "اكتشاف مسارات التنفيذ المخفية",
      "حل تحديات CTF المعقدة",
      "أتمتة اكتشاف الثغرات",
    ],
  },
  {
    id: "apkleaks",
    name: "APKLeaks",
    tagline: "كشف المعلومات المسرّبة",
    description: "يكشف URLs, IPs, API keys, secrets من APK باستخدام patterns قابلة للتخصيص.",
    category: "Forensics",
    level: "Beginner",
    platform: "Linux / macOS / Windows",
    website: "github.com/dwisiswant0/apkleaks",
    author: "dwisiswant0",
    stars: "4k+",
    commands: [
      "apkleaks -f app.apk",
      "apkleaks -f app.apk -o results.json",
    ],
    features: [
      "كشف API keys و Secrets",
      "كشف URLs و IPs",
      "Patterns قابلة للتخصيص",
      "دعم التقارير بصيغة JSON",
    ],
    useCases: [
      "بحث عن تسريبات البيانات",
      "فحص أولي لأمن التطبيق",
      "Bug Bounty",
    ],
  },
  {
    id: "bytecodeviewer",
    name: "Bytecode Viewer",
    tagline: "6 مفككات في واجهة واحدة",
    description: "يعرض JADX + Procyon + CFR + Fernflower + Krakatau + Smali معاً لمقارنة نتائج المفككات المختلفة.",
    category: "Static",
    level: "Beginner",
    platform: "Windows / macOS / Linux",
    website: "github.com/Konloch/bytecode-viewer",
    author: "Konloch",
    stars: "15k+",
    commands: [
      "java -jar Bytecode-Viewer.jar",
    ],
    features: [
      "يجمع 6 مفككات Java",
      "مقارنة النتائج جنباً إلى جنب",
      "واجهة رسومية سهلة",
      "دعم Android APKs",
    ],
    useCases: [
      "تحليل الكود عند فشل JADX",
      "فهم الاختلافات بين المفككات",
      "التعليم والتدريب",
    ],
  },
  {
    id: "house",
    name: "House",
    tagline: "Frida GUI تفاعلي",
    description: "واجهة ويب لـ Frida تتيح اختبار API hooks بسهولة ومتكاملة مع objection.",
    category: "Dynamic",
    level: "Advanced",
    platform: "Linux / macOS",
    website: "github.com/nccgroup/house",
    author: "NCCGroup",
    stars: "1.5k+",
    commands: [
      "python3 house.py",
    ],
    features: [
      "واجهة ويب لـ Frida",
      "اختبار API hooks بسهولة",
      "متكامل مع objection",
      "توليد scripts Frida تلقائياً",
    ],
    useCases: [
      "تبسيط استخدام Frida",
      "مراقبة API calls بصرياً",
      "تطوير scripts Hooking سريعة",
    ],
  },
  {
    id: "sslkillswitch3",
    name: "SSL Kill Switch 3",
    tagline: "iOS SSL Pinning Bypass",
    description: "يوقف SSL Pinning على iOS بضغطة واحدة، يعمل مع كل frameworks iOS.",
    category: "Dynamic",
    level: "Advanced",
    platform: "iOS (Jailbreak)",
    website: "github.com/evilpenguin/SSLKillSwitch3",
    author: "EvilPenguin",
    stars: "2k+",
    commands: [
      "// يتم تفعيله من الإعدادات في iOS",
    ],
    features: [
      "إبطال SSL Pinning بضغطة واحدة",
      "دعم كامل لـ iOS 15+",
      "يعمل مع NSURLSession و NSURLConnection",
      "يدعم تطبيقات الطرف الثالث",
    ],
    useCases: [
      "تحليل حركة المرور المشفرة على iOS",
      "اختبار الأمان لتطبيقات آيفون",
    ],
  },
  {
    id: "jadxai",
    name: "Jadx-AI",
    tagline: "JADX مع ذكاء اصطناعي",
    description: "يضيف AI analysis لنتائج JADX، يشرح الكود تلقائياً ويكتشف الـ patterns الأمنية.",
    category: "Static",
    level: "Beginner",
    platform: "Windows / macOS / Linux",
    website: "github.com/LaurieWired/JADXecute",
    author: "LaurieWired",
    stars: "2k+",
    commands: [
      "jadx-gui --ai",
    ],
    features: [
      "شرح الكود بالذكاء الاصطناعي",
      "اكتشاف الـ patterns الأمنية",
      "تحليل وظائف الدوال المعقدة",
      "تكامل مع OpenAI/Ollama",
    ],
    useCases: [
      "فهم سريع للكود المعقد",
      "تحديد مواضع الثغرات بسرعة",
      "أتمتة شرح منطق التطبيق",
    ],
  },
];
